### ISSUE TITLE
Create a pipeline to send reminders to authors that have not submitted or have incomplete submissions

### ISSUE THREAD

**Issue by valearna** [WormBase/author-first-pass#101]
If an author has not submitted after a certain amount of time after we sent her the first afp email

**Comment by draciti** [comment]
Hi Valerio, 
is this ready to go in production?
Will this reach all the authors that have not responded so far?

Let us know how/if we should test this

**Comment by valearna** [comment]
I'm testing this pipeline and I'm actively working on it. No need to test it from your side.

**Comment by valearna** [comment]
The pipeline is in production and the first round or reminders went out yesterday

**Comment by draciti** [comment]
great! Closing
