### ISSUE TITLE
WBPaper00049559 - extraction of species and strain N2

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/author-first-pass#103]
This paper met the species and strain threshold for C. elegans and N2, respectively, but we didn't extract either.

**Comment by valearna** [comment]
pdf to text conversion problem. Whitespaces are not recognized correctly and part of the main text (not all) appears as a single string without whitespaces.

**Comment by draciti** [comment]
same issue as #104 for species. not solving the N2 problem
