### ISSUE TITLE
WBPaper00054648 - didn't extract C. elegans as species

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/author-first-pass#104]
Just looking over one of the author submissions, WBPaper00054648 and saw that the pipeline didn't extract C. elegans as a species for this paper, although some version of 'elegans' is mentioned 58 times.

The author did add it.

**Comment by draciti** [comment]
FYI also Paper 00054817 had 32 mentions of elegans and it was not extracted

**Comment by valearna** [comment]
Modifying the regex to capture matches to species not surrounded by whitespaces is not feasible. This is a pdf to text conversion issue.

**Comment by draciti** [comment]
this might be resolved when we will assign c elegans by default. @vanaukenk I leave it up to you if closing this ticket
