### ISSUE TITLE
Add entity threshold information to dashboard

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/author-first-pass#105]
Following on from our discussions at the IWM, it would be nice to list the current entity thresholds somewhere on the dashboard so @draciti and I can quickly access the values when analyzing results.

Here's the list I took from the Google spreadsheet, with an updated species value (from 3 to 10):

Datatype: threshold (CURRENT)
--
gene: 2
protein: 2
allele: 2
strain: 1
species: 10
transgene: 1

Thx.

**Comment by valearna** [comment]
add this info to the paper lists page

**Comment by draciti** [comment]
looks good to everyone, closing
