### ISSUE TITLE
Make the 'your afp papers' page more clear to the user

### ISSUE THREAD

**Issue by valearna** [WormBase/author-first-pass#115]
From discussion with Raymond:

The page can be a bit confusing for the user, especially if there are no afp papers for him/her. It would be easier to understand if we showed all the WormBase papers for the user and add a link for those with an AFP form. Also, having more text on the page explaining what the user is supposed to find in the page would help.

**Comment by vanaukenk** [comment]
Below is a list of papers for which you are an author and that have been processed by the new WormBase Author First Pass data flagging pipeline.  
To verify the flagged data, please click on the link to your paper.
Thank you for helping WormBase curator your paper!

**Comment by draciti** [comment]
What is Author First Pass: Wormbase processes your recently published papers and: 
1) extracts known entities such as gene names, strains and alleles
2) flags the paper as containing a specific datatype, e.g. gene expression or phenotype data
3) gives you the opportunity to add entities and information that will appear in WormBase

**Comment by vanaukenk** [comment]
The WormBase Author First Pass pipeline is a way for WormBase to identify entities (e.g. genes) and data types (e.g. genetic interactions) found in newly published papers.  The pipeline uses the Textpresso Central text mining system and approved C. elegans nomenclature to flag papers for curation by WormBase curators.  Verification of flagged data by authors helps prioritize papers for curation and provide feedback to improve the system.

**Comment by draciti** [comment]
looks good, closing
