### ISSUE TITLE
create a new page on the dashboard to list papers with submitted data by data type

### ISSUE THREAD

**Issue by valearna** [WormBase/author-first-pass#116]
can be similar to the curation status form, where there is a list of checkboxes with data types that can be selected. It can also have a checkbox to include partial submissions.

**Comment by valearna** [comment]
add checkboxes to filter for "curated" or "not curated" based on curation status form data. Also validated positive/negative.

Postgres table for curated papers: pap_curation_done

**Comment by valearna** [comment]
Ready to test. Filters on curation status are still not there, but those on SVMs and manual flagging are ready

**Comment by draciti** [comment]
thanks @valearna, looks good!
While I was going through the list of papers yesterday, I have noticed that many are flagged for human disease.
Now that we have the filter and will be easier for curators to get the lists, I think it's worth to ask Ranjana to validate what the authors have flagged positive for human disease so we can better tailor the description of what we want in the interface.
what do you @valearna and @vanaukenk  think?

**Comment by valearna** [comment]
I agree @draciti. I think that it would be important to have curator feedback at this point, especially for human disease

**Comment by vanaukenk** [comment]
@draciti @valearna 
Yes, I agree.
Human disease relevance seems to be the most popular for manually flagged data types, and it's probably better to ask Ranjana sooner rather than later.  
We could discuss at today's Textpresso meeting?

**Comment by draciti** [comment]
agreed

**Comment by valearna** [comment]
Added filters to exclude papers already curated for one or more data types. Ready to test on development site http://textpressocentral.org:3001 @draciti @vanaukenk

**Comment by draciti** [comment]
Hi @valearna, I started double checking the papers that were flagged by author and not curated using the filter for curator but 3 papers out of 4 were curated.
00054648
00054685
00056066
I did not go on checking the others as there might be a bug
Can you please take a look?

**Comment by valearna** [comment]
I don't see those IDs in the cur_curdata table for cur_datatype 'otherexpr'. Maybe I'm looking at the wrong table?

**Comment by draciti** [comment]
<img width="1226" alt="Screen Shot 2020-01-31 at 3 35 50 PM" src="https://user-images.githubusercontent.com/901243/73576137-6bc62e80-443f-11ea-98f7-e43203505ebb.png">

**Comment by draciti** [comment]
We need to check the 'OA value' in the curation status form. Screenshot above. Try to ask Juancarlos to which table it corresponds

**Comment by valearna** [comment]
Thanks @draciti, I emailed Juancarlos

**Comment by azurebrd** [comment]
Wrote a long reply to Valerio, but basically it's best to query through the form, as different datatypes are stored in different OA tables, and possibly other postgres non-OA tables, and even flatfiles for some curators's manual data.  But other 'otherexpr' it's exp_paper

**Comment by valearna** [comment]
Added function to get list of curated papers from the curation status form. Can you test the filters on the dev site @draciti @vanaukenk ? http://textpressocentral.org:3001/lists

**Comment by draciti** [comment]
Talked to @valearna: we need to exclude from the curated lists also the  papers that have been  validated negative  in the  curation status form.

http://mangolassi.caltech.edu/~postgres/cgi-bin/curation_status.cgi?action=listCurationStatisticsPapersPage&select_datatypesource=caltech&select_curator=two12028&listDatatype=otherexpr&method=allval%20neg&checkbox_cfp=on&checkbox_afp=on&checkbox_str=on&checkbox_svm=on

**Comment by draciti** [comment]
@valearna added the  list of papers validated negative. looks good
