### ISSUE TITLE
To improve author's response- list of e-mail addresses

### ISSUE THREAD

**Issue by draciti** [WormBase/author-first-pass#126]
@valearna is it possible to pull out the list of e-mail addresses of the people that have not submitted? Basically the ones listed in the 'Papers waiting for data submission'.

Currently, we need to click on every paper to see who was the author.

We might have done this type of extraction for the IWM but I am not 100% positive.

In this way we can easily see which persons did not respond and selectively ping some that we know (e.g. Paul Sternberg..)

**Comment by valearna** [comment]
We could create an additional tab to the new 'contributors' page with the list of email addresses emailed out but with no submissions

**Comment by draciti** [comment]
We are sending reminder e-mails now, can close
