### ISSUE TITLE
paper 56901 - nhr-47 extracted instead of csr-1

### ISSUE THREAD

**Issue by valearna** [WormBase/author-first-pass#131]
Check gene symbol-id map to see if the priorities are assigned correctly

**Comment by valearna** [comment]
Changed priority order for different gene types in gene symbol - gene ID mapping. Synonyms have now the lowest priority, followed by seqnames, gin_locus, and gin_wbgene. The change is now in production. Can you verify that this is not causing any side effect on the next round of papers @draciti @vanaukenk ?

**Comment by draciti** [comment]
this was solved by changing the priority order, closing
