### ISSUE TITLE
Paper 57005, gene extraction problem

### ISSUE THREAD

**Issue by draciti** [WormBase/author-first-pass#132]
@valearna this is for you to check:
The authors have added trx-1 ( WBGene00015062 ) and Removed: Bm1_46700A ( WBGene00222771 ): trx-1 is asynonym of Bm1_46700A: TAG2510, Bm1_46705, Bm1_46700A, trx-1.
It seems that instead of trx-1, the pipeline extracted Bm1_46700A. This might be fixed already as we changed the order of priorities, e.g. locus, sequence, synonym

Can you please check?

**Comment by valearna** [comment]
Thanks @draciti for bringing up this example. I ran the pipeline in debug mode on paper 57005 with the new priorities and I see trx-1 extracted instead of Bm1_46700A. This means that this issue is solved and won't affect future extractions.

**Comment by draciti** [comment]
Wonderful! closing
