### ISSUE TITLE
00056956- author added hsp-16.2, why?

### ISSUE THREAD

**Issue by draciti** [WormBase/author-first-pass#133]
I need someone else to check to make sure I have not gone blind.. I found just one occurrence of hsp-16.2 in the paper and it is in the references.
Not sure why the author added it
thanks

**Comment by vanaukenk** [comment]
That's all I can find, too - one mention in the references.  
I'd have to read the paper in detail to see if there was any other reason they might have added it.....

**Comment by draciti** [comment]
may  be an author typo. closing
