### ISSUE TITLE
New alleles submitted via AFP

### ISSUE THREAD

**Issue by draciti** [WormBase/author-first-pass#134]
Opening a ticket to not forget. We should think of how adding new alleles submitted by the authors. for now I think the only option is to request new names via the name server. 
It would be good to talk to Hinxton and see if this can be done 'in batch'

**Comment by draciti** [comment]
Talk to Hinxton and see if this process can be automated and talk to Karen in the conversation to see if there is an existing textpresso pipeline

**Comment by valearna** [comment]
Hinxton is using their own pipeline to process the data received from AFP emails and we don't need to communicate directly with the name server.

**Comment by valearna** [comment]
It seems that this is already covered by Hinxton. Can we close this issue @draciti @vanaukenk ?

**Comment by draciti** [comment]
good for me to close
