### ISSUE TITLE
e1364 not extracted- paper 56695

### ISSUE THREAD

**Issue by draciti** [WormBase/author-first-pass#135]
e1364 not extracted. @valearna can you pls take a look?

**Comment by draciti** [comment]
for the same paper, strain CB1364 not extracted.
We need to understand if there is a pattern for specific journals when extraction fails

**Comment by valearna** [comment]
I found only one mention to e1364 in the converted text and it's in this form: "daf-4(e1364)". Also for strain CB1364 it's a pdf to text conversion problem: I see the keyword surrounded by text without whitespaces.

**Comment by draciti** [comment]
another PDF to text conversion issue we cannot do much about (unless we move to open access). Closing
