### ISSUE TITLE
55920 entities not extracted

### ISSUE THREAD

**Issue by draciti** [WormBase/author-first-pass#136]
Genes:  
aat-6 ( WBGene00000007 )
snf-5 ( WBGene00004904 )

Alleles:
lg601 ( WBVar00088492 )

Strains: 
BR2742
JK574
N2

@valearna please check why it failed

**Comment by valearna** [comment]
pdf to text conversion issues. Only supplemental material was converted, but the main paper failed.

**Comment by draciti** [comment]
there was only the supplemental material, by solving issue #138 we took care of it
