### ISSUE TITLE
spe-6 not extracted from 54685

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/author-first-pass#137]
The spe-6 (WBGene00004960) was not extracted from WBPaper00054685 although it appears to have been mentioned 25 times.

This paper is from PLoS Biology.

**Comment by vanaukenk** [comment]
We also failed to extract three alleles for this paper that otherwise met the threshold:

hc163
ok1193
ok971

**Comment by valearna** [comment]
extraction of entities failed because of pdf to text conversion issues.

**Comment by draciti** [comment]
same as #135
