### ISSUE TITLE
Should we process papers if only supplemental material is extracted but not the main paper?

### ISSUE THREAD

**Issue by valearna** [WormBase/author-first-pass#138]
For some papers, pdf to text conversion failed for the main paper but went through for supplemental material. We are currently processing these papers, maybe hoping that the supplemental material mentions most of the entities involved in the study, but this can lead to extraction issues and missed entities. This is for example what happened with #136. Should we exclude papers when the main text is not converted @draciti @vanaukenk ?

**Comment by draciti** [comment]
I vote for excluding. What do you think @vanaukenk

**Comment by vanaukenk** [comment]
I agree with @draciti 
If we don't have the main paper, we should not process just the supplemental for AFP.

**Comment by valearna** [comment]
- keep track of bibliographic information for these papers and exclude them
