### ISSUE TITLE
add C. elegans to the species list by default

### ISSUE THREAD

**Issue by valearna** [WormBase/author-first-pass#143]
Make sure parasite papers are not included in the pipeline

**Comment by vanaukenk** [comment]
Looking at some parasite papers in postgres, it looks like they are not being handled consistently for various reasons.

In some cases, their primary/not primary status is actually 'not designated' so we wouldn't pick then up for AFP; in some cases there is a PDF, in others, there isn't.

I'll double-check the status of some parasite papers with status 'primary' and PDFs wrt the AFP pipeline.
