### ISSUE TITLE
add a tag to the ?Paper model to capture AFP information.

### ISSUE THREAD

**Issue by draciti** [WormBase/author-first-pass#144]
add a tag to the ?Paper model to capture AFP information so authors can be recognized on the paper page

**Comment by vanaukenk** [comment]
I am hoping to propose ?Paper model changes for the next upload and thought I'd propose the AFP tag at the same time.

I'm thinking something fairly straightforward like 'Author First Pass' as a tag that would be populated with a WBPerson ID.

@draciti @valearna - what do you think?  I'm open to other suggestions.

**Comment by draciti** [comment]
Sounds good to me @vanaukenk , thank you

**Comment by valearna** [comment]
sounds good to me too. Thanks!

**Comment by vanaukenk** [comment]
https://github.com/WormBase/wormbase-pipeline/issues/102

**Comment by valearna** [comment]
The tag is there, but we need to think about how to populate it.

**Comment by valearna** [comment]
use afp_contributor table. We can add old contributors to include submissions from old AFP.
