### ISSUE TITLE
Some gene entries not properly formatted in paper editor

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/author-first-pass#146]
![WBP57312_bogusGeneName](https://user-images.githubusercontent.com/1730534/71929464-abaf3400-3167-11ea-910e-70abd27581cc.png)

**Comment by valearna** [comment]
Genes in that format were messing up the AFP form. I fixed the UI to support them. I also updated the pap_gene table and fixed the wrong gene IDs

**Comment by valearna** [comment]
Tested by saving gene list through the afp UI to afp_genestudied table (save and continue button in the overview section) and to pap_gene (Finish and submit button).

**Comment by vanaukenk** [comment]
I've double-checked the papers.ace output and it looks fine now for WBPaper00057312.
@valearna - shall we close this ticket?
