### ISSUE TITLE
00057211 on dev site

### ISSUE THREAD

**Issue by draciti** [WormBase/author-first-pass#153]
I submitted data for 00057211 on dev site: http://textpressocentral.org:3001/home. 
I received an email 'New AFP data submission completed by author' with  the name of the corresponding author (I had changed the name to mine during the submission process)
Did something go wrong?

**Comment by draciti** [comment]
<img width="952" alt="Screen Shot 2020-02-24 at 11 09 01 AM" src="https://user-images.githubusercontent.com/901243/75174657-9b8eec00-56f6-11ea-89fd-235d4634b905.png">

**Comment by valearna** [comment]
Do you mean the field 'corresponding author email' in the email? I think that the value for the corresponding author field should remain the original one, but I do not see your email as 'afp_contributor' in the database. I'm debugging right now.

**Comment by draciti** [comment]
I tried to submit again to see if you can  now see my email as 'afp_contributor' in the database. If so, we can  close this ticket

**Comment by draciti** [comment]
Closing this, see ticket #168, @valearna will  store the WBPerson instead of the email
