### ISSUE TITLE
Add a 'Help and more info' widget 

### ISSUE THREAD

**Issue by draciti** [WormBase/author-first-pass#159]
Add a widget below 'Comments and Submit' 
the widget will contain
- a link to the afp paper
- the help.afp email 
- a video  tutorial  to use AFP
- an FAQ section

**Comment by valearna** [comment]
Ready to test on the dev site. We need to add content to the 'FAQ' and 'Video tutorial' sections.

**Comment by draciti** [comment]
Put contact in the widget. Clicking on it will open the email contact as of right now

**Comment by valearna** [comment]
move 'contact us' to the menu, as we did for the webinar link

**Comment by draciti** [comment]
looks good. closing
