### ISSUE TITLE
Add button to request new WB person ID from author selection modal

### ISSUE THREAD

**Issue by valearna** [WormBase/author-first-pass#161]

**Comment by valearna** [comment]
@vanaukenk @draciti Is there a wormbase web page to request a new WBPersonID that we can link here? I can't find it on WB website.

**Comment by azurebrd** [comment]
https://wormbase.org//submissions/person.cgi

**Comment by valearna** [comment]
Thanks @azurebrd!

**Comment by azurebrd** [comment]
Not at all @valearna (I do'nt know why it pasted with double /   It works, but should be https://wormbase.org/submissions/person.cgi )

**Comment by draciti** [comment]
looks  good, closing
