### ISSUE TITLE
Text changes for V2.0

### ISSUE THREAD

**Issue by draciti** [WormBase/author-first-pass#163]
- [x] Overview widget: Change 'List of WormBase genes identified in the paper' with  'List of WormBase genes experimentally studied in the paper'  

- [x] Change the text in the question mark 'Please validate the list of  genes experimentally studied in  the paper in the box below by adding or removing genes  if required.'

- [x] Expression widget: The current Site  and Time of action text should have an  extra line: add after "...other similar experiments": Gene expression data alone is insufficient to indicate site/time of action pertaining to a specific phenotype.

- [x] Interaction widget: Genetic interactions: add question mark  with  this text: 'Genetic interactions refer to observations of phenotype modifications and/or a double mutant (or double genetic perturbation) phenotype that deviates from the expected phenotype based on single perturbation phenotypes, assuming the genes act independently.'

- [x] Interaction widget: Regulatory interactions: add question mark  with  this text: 'Regulatory interactions refer to observations of various perturbations (genetic or environmental) affecting the expression of a gene and/or the localization of a gene product.'

- [x] Interaction widget: Physical interactions: add question mark  with  this text: 'Physical interactions represent molecular associations between C. elegans genes and gene products (protein-protein, DNA-protein, RNA-protein). Please don’t include chemical-gene interactions and inter-species interactions."

- [x] Disease: The paper describes an experimental model for a specific human disease (e.g., Parkinson’s disease) by employing _at least_ one of the following:
Gene/allele or strain that recapitulates disease phenotype(s) and provides insight into disease pathogenesis. Please provide official names for strains (e.g., CL2006).
Transgenic studies with human and/or worm disease relevant gene.
Modifiers of a new or previously established disease model (e.g., drugs, herbals, chemicals, etc).

**Comment by valearna** [comment]
For future development, we would like to have a UI component to specify which species some datatypes such as interactions are related to, with a checkbox for each and maybe an 'all species' checkbox

**Comment by draciti** [comment]
Looks good, closing
