### ISSUE TITLE
store WBPerson IDs in afp_contributor tables instead of email addresses

### ISSUE THREAD

**Issue by valearna** [WormBase/author-first-pass#168]

**Comment by draciti** [comment]
discussed. it will be relevant once we will dump the data into an ace file

**Comment by vanaukenk** [comment]
@valearna 
I was going to ask Juancarlos to update the paper dumping script to populate the Author_first_pass ?Person value with the WBPerson id of the submitter for WS279, but when I query the afp_contributor table on tazendra, I still see the authors email addresses and not a WBPerson id.
Does the value we're storing still need to be changed from email to WBPerson?  
Thx.

**Comment by valearna** [comment]
The form in production is still saving email addresses to tazendra, so if I switch to person IDs now we may end up with a mix of addresses and IDs in the table. Would it be ok if we switch as soon as we release the new version?

**Comment by vanaukenk** [comment]
@valearna 
Sure, that would be fine.
I was wondering about this since we are close to the WS279 upload.
Thx.

**Comment by valearna** [comment]
@vanaukenk the table is ready
