### ISSUE TITLE
Add a field 'Other gene function'  in the AFP form

### ISSUE THREAD

**Issue by draciti** [WormBase/author-first-pass#169]
In the 'Phenotypes and Function' widget': in the 'Functional data in the paper' box,  add a checkbox called 'Other gene function' with  a free text box underneath.
If not clear enough, ask us :)

(this is to respond to a user comment)

**Comment by valearna** [comment]
We need a new table to store the data coming from the new 'other gene function' checkbox. @azurebrd can you set it up on tazandra and mangolassi? @draciti @vanaukenk do you have a preferred name for the new table?

**Comment by valearna** [comment]
@azurebrd can you create a new table afp_othergenefunc?

**Comment by valearna** [comment]
Add the new data type to the dashboard

**Comment by vanaukenk** [comment]
As part of v3 testing on 59408, checked other gene function box and left a comment; all fine on corresponding dashboard entry.
