### ISSUE TITLE
Receiving an email notification when the 'comments' box is filled out

### ISSUE THREAD

**Issue by draciti** [WormBase/author-first-pass#170]
@valearna , Kimberly and I were wondering if  there is already a mechanism in place for both of us to receive a notification when the comments  box is filled out. If not, can  you please set this  up?
Receiving a direct notification for comments will allow us to monitor closely if the authors have specific issues that should be addressed right away and can help us continue developing the FAQs.
thanks!

**Comment by valearna** [comment]
There are two mechanisms we could use for this: the digest emails and the submission notification emails. Digest emails are sent out weekly and contain a list of 'positive' paper ids for a certain datatype, including the free text provided by the authors. The submission notification emails are sent out as soon as the author submits the data and we could modify them to report any comments by the authors.

**Comment by valearna** [comment]
On 08/21 we verified that the notification system is already in place and there is no need for additional changes.
