### ISSUE TITLE
add tazendra user and passwd to jenkins config for afp pipeline

### ISSUE THREAD

**Issue by valearna** [WormBase/author-first-pass#172]
To be done before release

**Comment by azurebrd** [comment]
Which user password ?

**Comment by valearna** [comment]
@azurebrd The new pipeline makes url requests to download pdfs from tazendra passing username and password to the requests. This is to avoid auth errors when on a VPN IP address not in tazedra's whitelist. This ticket is a reminder for me to modify the configuration on jenkins to pass the username and password as arguments to the pipeline before releasing version 2.0.

**Comment by azurebrd** [comment]
@valearna Oh, is that for authors to see the PDFs or curators ?  In theory curators should be able to login and download, and I don't think we're supposed to let non-Caltech people see the PDFs (although we probably have).  I'm assuming that even though the user/pass are stored somewhere, it's secure ?

**Comment by valearna** [comment]
@azurebrd This is only for the pipeline, which does not give access to the pdfs for curators or authors. The pipeline runs in the background weekly, fetches newly added pdfs from tazendra, extracts entities and stores them to postgres. Username and password will be stored in jenkins config file, which is on textpressocentral server and secured by authentication.

**Comment by azurebrd** [comment]
@valearna ooooh, cool cool, thanks.  I'd thought the pipeline would get the text from the papers from textpresso.  I didn't realize that this was an update to that pipeline, or that it had to be separate for some reason.

**Comment by valearna** [comment]
@azurebrd we are working on a major update to the pipeline and I added this feature since I first encountered the VPN issue few months ago. We get the pdfs from tazendra instead of textpresso since in some cases textpresso fails to convert the pdf to text, but we are able to do the conversion through a python library.
