### ISSUE TITLE
Is change user functionality working on the development site?

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/author-first-pass#174]
@valearna 

I was testing the Change user functionality on the development site and wasn't able to change the user even though I had selected a new user name from the autocomplete.

Is this functionality enabled on the development site?

Thx.

**Comment by vanaukenk** [comment]
Ah....I see now that I need to double-click on the selected name in the autocomplete.

Maybe we should add a submit or change button to the pop-up window to make this clearer?

**Comment by valearna** [comment]
Good point @vanaukenk, I'll add a button to enable single click on the name and 'submit' with the button.

**Comment by vanaukenk** [comment]
Thanks @valearna !

**Comment by valearna** [comment]
ready to test on dev @vanaukenk
