### ISSUE TITLE
investigate if is better to use Allele or Variation throughout the form

### ISSUE THREAD

**Issue by draciti** [WormBase/author-first-pass#177]

**Comment by draciti** [comment]
Also consider to parenthetically list the contents of the Genetics and Reagents widgets in the left hand menu e.g. Genetics (alleles and strains)

**Comment by vanaukenk** [comment]
From the Alliance:
https://docs.google.com/document/d/1yIBZOIEUG_dPCLGTIWuJfrj3Sho91PT9Pc1o29Ew-qc

**Comment by draciti** [comment]
We will use allele
