### ISSUE TITLE
sort contributors by number of submissions in dashboard contributors page

### ISSUE THREAD

**Issue by valearna** [WormBase/author-first-pass#179]

**Comment by draciti** [comment]
reopening, having issues with the dashboard: http://textpressocentral.org:3001/contributors?paper_id=00059841

TypeError: undefined is not an object (evaluating 'payload.from = offset')

**Comment by valearna** [comment]
Bug fixed. Ready to test

**Comment by draciti** [comment]
looks good. Closing
