### ISSUE TITLE
Add link to paper editor in dashboard

### ISSUE THREAD

**Issue by valearna** [WormBase/author-first-pass#181]
Suggested by @rankishore

**Comment by draciti** [comment]
Ask Ranjana what would be the use case

**Comment by draciti** [comment]
we propose to add a link to the curation status form for each specific paper in the 'Paper info' window. 
this is related to this ticket and #184 
Talk to Ranjana about this

**Comment by draciti** [comment]
link to paper editor itself is not necessary, we will  link to the curation status form
