### ISSUE TITLE
Exclude two strains from AFP display

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/author-first-pass#191]
Hi,

There are two WBStrains that we should add to an exclusion list to avoid displaying on the AFP form:

M9 (WBStrain00043982)

OH (WBStrain00046993)

Thx.

**Comment by valearna** [comment]
Done

**Comment by valearna** [comment]
Leaving this open for future additions

**Comment by vanaukenk** [comment]
Paper 59408 has five mentions of 'M9' but M9 does not appear in the strain list so the exclusion list is working correctly for M9.

None of my test papers had 'OH' as a possible match (provided search is case-sensitive).

Note that Aric was going to remove OH from the CGC strain record, but that may not have happened until after WS281 data upload; check again when WS282 is on staging.  https://github.com/WormBase/website/issues/7170

A search of 'OH' on the CGC site returns only OH strains followed by a number; no record is there for just 'OH'.
