### ISSUE TITLE
Strains stored with utf-8 characters are saved correctly but displayed with wrong characters when loaded

### ISSUE THREAD

**Issue by valearna** [WormBase/author-first-pass#192]

**Comment by valearna** [comment]
The first_pass_api on tazendra and mangolassi returns garbled text if utf-8 characters are present in the text stored in the db. http://mangolassi.caltech.edu/~azurebrd/cgi-bin/forms/textpresso/first_pass_api.cgi?action=jsonPaper&paper=00060799&passwd=1617330871.3572838

**Comment by azurebrd** [comment]
Should be fixed now.

**Comment by valearna** [comment]
Thanks @azurebrd, I can see the UTF-8 characters correctly now

**Comment by draciti** [comment]
@valearna , I wanted to test this  on  Peter Douglas submission but  I don't see a link to the AFP form on dev

http://textpressocentral.org:3001/paper?paper_id=00061115

Is  this  because the paper is not processed on dev?  Let me know if I should test this  on any other paper.
thanks

**Comment by valearna** [comment]
Dev is linked to mangolassi and that specific paper was not processed there. I can manually add the paper if you need to work on that specific one, otherwise you can test the functionality on any other paper on dev.

**Comment by draciti** [comment]
I'll test on another paper. thanks
________________________________

**Comment by draciti** [comment]
@valearna looks good on the UI after I save the data.
Can you double check that the data is saved correctly on mangolassi?
I edited the strain field (New strains)
thanks

http://textpressocentral.org:3000/genetics?paper=00059841&passwd=1600893658.7796698&title=RPamide%20neuropeptides%20NLP-22%20and%20NLP-2%20act%20through%20GnRH-like%20receptors%20to%20promote%20sleep%20and%20wakefulness%20in%20C.%20elegans.&journal=Sci%20Rep&pmid=32555288&doi=10.1038/s41598-020-66536-2&personid=11490&hide_genes=false&hide_alleles=false&hide_strains=false

**Comment by valearna** [comment]
The data looks good on mangolassi:

select * from afp_otherstrain where joinkey = '00059841';

00059841 | [{"id":1,"name":"PMD101 (utsEx9[rgef-1p::FLAG::PMK-1::mCherry::unc-54 3’ UTR + unc-119(+)]; unc-119(ed3) III)"},{"id":2,"name":"PMD106 (utsEx10[sur-5p::FLAG::PMK-1::mCherry::unc-54 3’ UTR + unc-119(+)]; unc-119(ed3) III)"},{"id":3,"name":"PMD107 (utsEx11[rgef-1p::FLAG::VHP-1::mCherry::unc-54 3’ UTR + unc-119(+)]; unc-119(ed3))"},{"id":4,"name":"PMD117 (utsEx13[sur-5p::FLAG::VHP-1::mCherry::unc-54 3’ UTR + unc-119(+)]; unc-119(ed3)) "},{"id":5,"name":"PMD13 (rrf-3(b26) II; egIs1 [dat-1p::GFP])"},{"id":6,"name":"PMD14 (rrf-3(b26) II; fem-1(hc17) IV; juIs76 [unc-25p::GFP + lin-15(+)] II)"},{"id":7,"name":"PMD60 (rrf-3(b26) II; egIs1 [dat-1p::GFP]; uIs69 [(pCFJ90) myo-2p::mCherry + unc-119p::sid-1])"},{"id":8,"name":"PMD63 (rrf-3(b26) II; egIs1 [dat-1p::GFP]; sid-1(pk3321) V; uIs69 [pCFJ90 (myo-2p::mCherry) + unc-119p::sid-1])"},{"id":9,"name":"PMD152 (sid-1(qt9) V; egIs1 [dat-1p::GFP]; uthIs237[myo-3p::tomato, myo-3p::sid-1])"},{"id":10,"name":"PMD153 (vhp-1(sa366) II; egIs1 [dat-1p::GFP]) "},{"id":11,"name":"PMD62 (kgb-1(um3) IV; egIs1 [dat-1p::GFP]"},{"id":12,"name":"PMD173 (math-33(ok2974); egIs1 [dat-1p::GFP])"},{"id":13,"name":"PMD112 (rrf-3(b26); egIs1 [dat-1p::GFP]; utsEx11 [rgef-1p::FLAG::VHP-1::mCherry + Cbr-unc-119(+)]"}] | 2021-04-22 10:58:54.402694-07

**Comment by draciti** [comment]
perfect, closing
