### ISSUE TITLE
Remove double WBGene prefix from AFP feedback from on dev (wbtools branch)

### ISSUE THREAD

**Issue by valearna** [WormBase/author-first-pass#196]

**Comment by draciti** [comment]
Looks good, closing
<img width="630" alt="Screen Shot 2021-04-21 at 9 14 17 AM" src="https://user-images.githubusercontent.com/901243/115568593-106d9f80-a282-11eb-9acc-fb3d43f5b874.png">
tested on dev for this paper: http://textpressocentral.org:3001/paper?paper_id=00059841
