### ISSUE TITLE
Improve add from lists

### ISSUE THREAD

**Issue by draciti** [WormBase/author-first-pass#198]
Authors can add only one entity at a time, and need to go back to the dashboard after adding and need to click again the plus button. Too many clicks.

<img width="612" alt="Screen Shot 2021-04-23 at 8 50 17 AM" src="https://user-images.githubusercontent.com/901243/115881387-4d1bd100-a411-11eb-96c9-6bfd9a365f9d.png">

**Comment by valearna** [comment]
We could integrate the form that is now in the popup window directly in the main select component, but we need to make sure that the resulting 'merged' component is not confusing

**Comment by valearna** [comment]
A prototype is ready on dev

**Comment by valearna** [comment]
As discussed on 04/30/2021, we need to implement the following changes:
- sort autocomplete results by exact match first
- add checkbox to select exact match only (default to False)
- add linkout to gene name sanitizer from 'upload list of gene IDs' to convert gene names into IDs
- separate input for autocomplete by comma OR newline and expand input

**Comment by valearna** [comment]
The new multiselect form is ready to test on http://textpressocentral.org:3000/ @draciti @vanaukenk. You can reach the dev form for a real paper through the dev dashboard on http://textpressocentral.org:3001/

**Comment by valearna** [comment]
The autocomplete is now faster thanks to the caching mechanism provided by react-query (https://react-query.tanstack.com/)

**Comment by valearna** [comment]
Add question mark to the gene name sanitizer link with this text: "Screen a list of C. elegans gene names and identifiers to find whether they were renamed, merged, split, or share sequence with another gene"

**Comment by valearna** [comment]
Question mark added. Ready to test

**Comment by draciti** [comment]
looks good. closing

**Comment by vanaukenk** [comment]
Reopening this ticket as we may want to discuss further and make some modifications as a result of v3 testing.

**Comment by draciti** [comment]
@valearna , looks great!

Kimberly and I went through the form once more. Here are the proposed tweaks.

**Gene section**
- [ ] 'Remove selected' -> change  to 'Remove Genes' to keep the language similar to 'Add Genes'
- [ ] Add a pop-up on remove selected with this text 'Select the genes you want to remove and click on 'Remove Genes''
- [ ] Show 'Show selected on WormBase' by default
- [ ] move export.txt button below the box next to 'Show selected on WormBase' 
- [ ] Change instructions on box 'Autocomplete on one or more...' with 'Enter one or more gene name or ID, e.g. unc-26 or WBGene00006763, separated by comma, white spaces, or new line.  Then, select from the autocomplete list and click on 'Add selected'.
- [ ] Have 'Exact match only' checked by default
- [ ] Add pop-up on 'Exact match only' with the following text 'Uncheck this option to see genes from more species'
- [ ]  Remove case sensitivity for genes autocomplete

**Species section**

- [ ] 'Remove selected' -> change  to 'Remove Species' to keep the language similar to 'Add Species'
- [ ] move export.txt button below the box  
- [ ] Add a pop-up on remove selected with this text 'Select the species you want to remove and click on 'Remove Species''
- [ ] Change instructions on box 'Autocomplete on one or more...' with 'Enter one or more species name, e.g. Caenorhabditis elegans, separated by comma, white spaces, or new line.  Then, select from the autocomplete list and click on 'Add selected'.
- [ ] Improve autocomplete from species (ticket #218 )
- [ ] Have 'Exact match only' checked by default
- [ ] Remove case sensitivity for Species autocomplete

**Alleles section**

- [ ] 'Remove selected' -> change  to 'Remove Alleles' to keep the language similar to 'Add Alleles'
- [ ] move export.txt button below the box 
- [ ] Add a pop-up on remove selected with this text 'Select the alleles you want to remove and click on 'Remove Alleles''
- [ ] Change instructions on box 'Autocomplete on one or more...' with 'Enter one or more allele name or ID, e.g. e1000 or WBVar00143672, separated by comma, white spaces, or new line.  Then, select from the autocomplete list and click on 'Add selected'.
- [ ] Have 'Exact match only' checked by default
- [ ] Remove case sensitivity for allele autocomplete

**Strains section**

- [ ] 'Remove selected' -> change  to 'Remove Strains' to keep the language similar to 'Add Strains'
- [ ] move export.txt button below the box 
- [ ] Add a pop-up on remove selected with this text 'Select the strains you want to remove and click on 'Remove Strains''
- [ ] Change instructions on box 'Autocomplete on one or more...' with 'Enter one or more Strain name or ID, e.g. CB1001 or WBStrain00004222, separated by comma, white spaces, or new line.  Then, select from the autocomplete list and click on 'Add selected'.
- [ ] Remove case sensitivity for strain autocomplete

**Transgenes section**

- [ ] 'Remove selected' -> change  to 'Remove Transgenes' to keep the language similar to 'Add Transgenes'
- [ ] move export.txt button below the box 
- [ ] Add a pop-up on remove selected with this text 'Select the transgenes you want to remove and click on 'Remove Transgenes''
- [ ] Change instructions on box 'Autocomplete on one or more...' with 'Enter one or more Transgene name or ID, e.g. inIs179 or WBTransgene00000647, separated by comma, white spaces, or new line.  Then, select from the autocomplete list and click on 'Add selected'.
- [ ] Remove case sensitivity for transgene autocomplete
