### ISSUE TITLE
Add links to curation status form

### ISSUE THREAD

**Issue by draciti** [WormBase/author-first-pass#200]
We will put links to the curation status form. 

There will be 2 types of links: 
- one at the bottom of the paper list, the link will  open all the papers in the list the  curation status form 
-  one  on the paper info tab. This is an individual link to the paper in the curation status form

**Comment by valearna** [comment]
Since CSF needs a curator ID, we decided to avoid adding these links since it's relatively easy to open the CSF with a specific paper ID and managing curators from the dashboard would require additional work
