### ISSUE TITLE
Add link to curation status form for single papers and "all papers" in weekly digests

### ISSUE THREAD

**Issue by valearna** [WormBase/author-first-pass#201]
- single paper link opens csf for that specific paper
- link to open all papers in the email

**Comment by valearna** [comment]
The curation status form needs a curator ID to keep track of 'who did what' in the database. If we link to the csf from the AFP emails, we need to specify the curator ID that we want to use. This might be doable from the emails, since we know the mapping between curators email and their IDs, but it is not feasible from the AFP dashboard since we don't have individual logins. At this point I don't know how to proceed, as adding links to the csf may create issues if there is not an easy way to change the curator id from the csf results page

**Comment by azurebrd** [comment]
Could you add a select field to the dashboard where a curator could just click their name, and tack that on to the link to the csf ?  Or is there some ideological reason not to have that on that form ?

**Comment by valearna** [comment]
Thanks @azurebrd. Yes, we can read the list of curators and show it in the AFP dashboard as a select field

**Comment by valearna** [comment]
on July 16, we decided to leave the notification emails as they are and not add links to the curation status form
