### ISSUE TITLE
Add instructions for authors for Strain and Variation sections

### ISSUE THREAD

**Issue by draciti** [WormBase/author-first-pass#203]
We want to capture genotype info for strains, variations, and transgenes, also species.
Add a sentence to explain to authors how to enter the  data:
_Enter the strain name followed by genotype followed by species, separated  by comma.
e.g. PMD153, (vhp-1(sa366) II; egIs1 [dat-1p::GFP]), C. elegans_

@draciti find a couple of examples for alleles, one CRISPR and a regular one
find also an example for transgenes

**Comment by draciti** [comment]
Text for New Alleles box:
e.g. _dpy-5(e61), C.elegans_
CRISPR alleles: e.g. _bus-50(e5001[bus-50::gfp]), C. elegans_

Text for New Strains box:
e.g. PMD153, _(vhp-1(sa366) II; egIs1 [dat-1p::GFP]), C. elegans_

Text for New Transgenes box:
e.g.: _eaIs15, [Ppie-1::HIM-5::GFP::pie-1], C. elegans_

@vanaukenk  please take a look.
A couple of questions:
1. In the proposal at the beginning of the ticket wa wanted to add a sentence such as: _Enter the strain name followed by genotype followed by species, separated by comma._
Are we still keeping the sentence or shall  we simply put the example?
2. Do we need to check in with Paul D to see if the examples are ok? I took  the  allele examples from the WB  nomenclature page.
3. For transgenes do we want to include an extrachromosomal example as well?

Thanks

**Comment by vanaukenk** [comment]
Thanks @draciti   These look good.

For the questions:

1. I'd keep the sentence; it could be helpful.  And maybe we should even write a sentence for alleles (and transgenes), e.g. Enter the gene name followed by the allele in parentheses; for CRISPR alleles, include the knock-in construct.  (If that makes sense).
2. We could always double-check with Paul D. just to make sure these look okay and maybe also to see if we need to update the WB nomenclature page to include CRISPR alleles.
3. Good idea - an extrachromosomal example, if curators will want them, would be good.

**Comment by draciti** [comment]
Writing the updated text here not to lose track, will also send to Paul D via email:
Text for New Alleles box:
_Enter the gene and allele name followed by species, separated by comma._
e.g. _dpy-5(e61), C.elegans_
_For CRISPR alleles include the knock-in construct, followed by species, separated by comma._ 
e.g. _bus-50(e5001[bus-50::gfp]), C. elegans_

Text for New Strains box:
_Enter the strain name followed by genotype followed by species, separated by comma._
e.g. PMD153, _(vhp-1(sa366) II; egIs1 [dat-1p::GFP]), C. elegans_


Text for New Transgenes box:
_Enter the transgene name followed by genotype followed by species, separated by comma._
e.g.: _eaIs15_, _[Ppie-1::HIM-5::GFP::pie-1], C. elegans_
For extrachromosomal arrays: _sqEx67, [rgef-1p::mcherry::GFP::lgg-1 + rol-6], C. elegans_

**Comment by draciti** [comment]
@valearna below the text suggestions, approved by Hinxton:

Text for New Alleles box:
_Enter the gene and allele name followed by strain and species, separated by comma._ 
e.g. _flu-4(e1004), CB1004, C.elegans_
_For CRISPR alleles include the knock-in construct, followed by species, separated by comma. 
e.g. bus-50(e5001[bus-50::gfp]), C. elegans_

Text for New Strains box:
_Enter the strain name followed by genotype followed by species, separated by comma._
e.g. PMD153, _(vhp-1(sa366) II; egIs1 [dat-1p::GFP]), C. elegans_


Text for New Transgenes box:
_Enter the transgene name followed by genotype followed by species, separated by comma._
e.g.: _eaIs15, [Ppie-1::HIM-5::GFP::pie-1], C. elegans_
_For extrachromosomal arrays: sqEx67, [rgef-1p::mcherry::GFP::lgg-1 + rol-6], C. elegans_

**Comment by draciti** [comment]
To discuss: ask to  specify species only for non elegans entities?
@valearna @vanaukenk

**Comment by draciti** [comment]
> Also, do we want authors to add strains for the CRISPR alleles as well?

Instructions updated below:
Text for New Alleles box:
_Enter the gene and allele name followed by strain and species, separated by comma._
e.g. _flu-4(e1004)_, CB1004, _C.elegans_
_For CRISPR alleles include the knock-in construct, followed by strain and species, separated by comma._
e.g. _hmg-3(bar24[hmg-3::3xHA]),_ BAT1560, _C. elegans_

Text for New Strains box:
_Enter the strain name followed by genotype followed by species, separated by comma._
e.g. _PMD153, (vhp-1(sa366) II; egIs1 [dat-1p::GFP]), C. elegans_

Text for New Transgenes box:
_Enter the transgene name followed by genotype followed by species, separated by comma._
e.g.: _eaIs15, [Ppie-1::HIM-5::GFP::pie-1], C. elegans_
_For extrachromosomal arrays: sqEx67, [rgef-1p::mcherry::GFP::lgg-1 + rol-6], C. elegans_

**Comment by draciti** [comment]
> As an author, I think I would find it easier if instructions were uniform, regardless of species.

Sounds good

**Comment by draciti** [comment]
Can Paul D implement a check to make sure entities will be captured correctly?
example, if an author does not include a strain
e.g. flu-4(e1004), C.elegans
Can  the script recognize that there is only one comma and output a warning  that one of the required fields is missing?
@Paul-Davis

**Comment by Paul-Davis** [comment]
@draciti I'm sure we can handle it

**Comment by draciti** [comment]
Enter the gene and allele name followed by strain and species, separated by comma. 
e.g. _flu-4_(_e1004_), CB1004, _C. elegans_. 
For CRISPR alleles include the knock-in construct, followed by strain and species, separated by comma. 
e.g. _hmg-3(bar24[hmg-3::3xHA]_), BAT1560, C. elegans.

**Comment by draciti** [comment]
Change text:
Enter one transgene per line.  If possible,...

that applies to transgenes, strains, alleles explanatory text. 
Also, New transgenes section C.  elegans should be italicized.

**Comment by draciti** [comment]
Looks good. Closing
