### ISSUE TITLE
Include catalytic activity neural network in the form

### ISSUE THREAD

**Issue by valearna** [WormBase/author-first-pass#205]
@vanaukenk evaluated ~260 papers (HIGH values only) and the precision is ~82%. If there's time, it would be good to include the NN values in the new release.

**Comment by valearna** [comment]
Add TPC Powered label

**Comment by vanaukenk** [comment]
The set of 10 test papers have 9 negative and 1 low value for the catalytic activity neural network.

Correctly, the data type is not flagged in the form for the papers I checked, but we should probably double-check one or more medium and high papers to make sure all is working as expected, i.e. only the high neural network papers are flagged in the AFP form.

**Comment by valearna** [comment]
I'll process some HIGH papers (to be taken from the curation status form)

**Comment by valearna** [comment]
@vanaukenk  I've just added a couple of papers positive for catalyticact:

https://tinyurl.com/ydsvasxk
https://tinyurl.com/ye6vo2j2

**Comment by vanaukenk** [comment]
Looks good so far in the form @valearna 

We'll just need to also migrate 'Enzymatic activity' from the Author Flagged column to the Automatically Flagged column on the dashboard.  

Thx.

**Comment by valearna** [comment]
Thanks @vanaukenk I moved 'Enzymatic activity' to Automatically flagged column and updated filter menu in the 'paper lists' dashboard page

**Comment by vanaukenk** [comment]
Thanks @valearna 
I can't see a specific paper in the test dashboard right now.
Are the updates in progress?

**Comment by valearna** [comment]
Yes, the dev api crashed after the latest update and I'm trying to figure out why. I'll notify you as soon as I can fix the issue

**Comment by valearna** [comment]
I've fixed the issue and the API is back

**Comment by vanaukenk** [comment]
Thanks @valearna 
All looks good, but looks like we also need to add 'Other gene function' to the Manually flagged data types filters under the Papers List widget.
Almost there..... :-)

**Comment by valearna** [comment]
you are right, I'll add it. Thanks @vanaukenk!

**Comment by valearna** [comment]
ready to test @vanaukenk

**Comment by vanaukenk** [comment]
Thanks @valearna 
I can see it there now!

**Comment by valearna** [comment]
can I close this issue @vanaukenk?
