### ISSUE TITLE
Update pipeline to contact all authors with an email address

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/author-first-pass#207]
In response to a question from the IWM 2021:

- [ ] Identify all authors
- [ ] Gather emails for as many authors as possible
- [ ] Modify email message to indicate that we're contacting as many authors as possible
- [ ] Send email to multiple authors

**Comment by draciti** [comment]
@valearna Valerio will do the testing as soon as we deploy

**Comment by valearna** [comment]
tested on production pipeline by checking if outreach gmail account had emails for all authors in the "sent" folder and by following the link in the emails. Everything looks good. Closing
