### ISSUE TITLE
Can't add single quotes to final comments

### ISSUE THREAD

**Issue by valearna** [WormBase/author-first-pass#208]
Adding quotes brakes the SQL query to insert comments

**Comment by valearna** [comment]
The issue affects most of the free text fields. Fixed by using psycopg2 functions to manage strings in SQL queries

**Comment by valearna** [comment]
It seems that the author form is ok but there are issues with the dashboard: http://textpressocentral.org:3001/paper?paper_id=00059442

**Comment by valearna** [comment]
I had to changed the escape function in the dashboard API to deal with quotes. Now everything looks good to me. You can continue testing the dashboard @draciti @vanaukenk

**Comment by vanaukenk** [comment]
I tested adding quotes and other special characters in the final comment of this paper:
http://textpressocentral.org:3001/paper?paper_id=00059413
Things look okay in the dashboard.

**Comment by draciti** [comment]
copy that. Closing
