### ISSUE TITLE
Duplicate paper objects submitted by author 

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/author-first-pass#209]
Hi,

In cleaning up paper objects for the Alliance migration, I found duplicate papers for which the same author submitted AFP data about one year apart.  

The author did slightly different things for each submission, and the most informative submission is probably a combination of the submitted data.

The two papers are: WBPaper00059172 and WBPaper00061047.

@valearna @draciti  Let me know if you want to discuss further at our regular meeting.  Otherwise, I can post what data I think we should keep and perhaps we can make a note somewhere of what happened.

**Comment by vanaukenk** [comment]
@valearna 

I wasn't sure how we left this ticket, but I just reviewed the submissions for these two papers since I'd like to merge them in postgres.  I'm planning to merge WBPaper00061047 into WBPaper00059172, but won't do that until everything is okay wrt the AFP data.

The data extracted is a little bit different from each paper, so I've tried to indicate below what we should keep in the AFP tables.  Let me know if anything doesn't make sense.

Genes - keep list from WBPaper00059172 (six more genes, five relevant)
Species - same for both, could keep either one
Alleles - keep one from WBPaper00061047
Strains - keep one from WBPaper00059172
Regulatory Interactions - keep data from WBPaper00061047 (author changed flagging)
Other gene function - keep data from WBPaper00061047 (author added data)
Comments - merge (slightly different comments from either submission)

Thank you!

**Comment by valearna** [comment]
Ok, thanks @vanaukenk, I'll copy the AFP data from WBPaper00061047 to WBPaper00059172 where you indicated that you prefer to keep WBPaper00061047.

**Comment by valearna** [comment]
I've just finished merging/updating the data. Can you check if everything looks good @vanaukenk?

**Comment by vanaukenk** [comment]
Looks perfect!  Thx @valearna

**Comment by vanaukenk** [comment]
I've just merged WBPaper00061047 into WBPaper00059172.
We can close this ticket whenever you're ready @valearna

**Comment by valearna** [comment]
Ok, closing.
