### ISSUE TITLE
Check if _proof papers are processed

### ISSUE THREAD

**Issue by valearna** [WormBase/author-first-pass#210]
there might be three cases:

_temp
_temp_proof
_proof <- check if this case exists and manage it

**Comment by valearna** [comment]
@vanaukenk  @draciti There are papers marked as _proof that are not _temp_proof. I've modified the library used to fetch pdfs from tazendra to mark both cases as proof and exclude them from the AFP pipeline.

**Comment by vanaukenk** [comment]
Thanks @valearna 
Shall we follow up with Daniel at all?

**Comment by valearna** [comment]
Yes @vanaukenk, we should discuss this with Daniel. It doesn't make much sense to me to have proofs that are not marked as temp, but Daniel can tell us if there's a difference between what he marks as _temp and _temp_proof.
