### ISSUE TITLE
Strain duplicates 

### ISSUE THREAD

**Issue by draciti** [WormBase/author-first-pass#220]
One strain was extracted (OH12312) for  [this paper](http://textpressocentral.org:3000/genetics?paper=00059841&passwd=1600893658.7796698&title=RPamide%20neuropeptides%20NLP-22%20and%20NLP-2%20act%20through%20GnRH-like%20receptors%20to%20promote%20sleep%20and%20wakefulness%20in%20C.%20elegans.&journal=Sci%20Rep&pmid=32555288&doi=10.1038/s41598-020-66536-2&personid=11490&hide_genes=false&hide_alleles=false&hide_strains=false)
Tried to add the same strain and see them as duplicates -see screenshot.
<img width="340" alt="Screen Shot 2021-08-24 at 9 05 02 AM" src="https://user-images.githubusercontent.com/901243/130631363-49ffa517-5e4f-45c6-9af0-8cf17fe8fafb.png">

Also, should we add WBstrain IDs next to the strains that were extracted?

**Comment by valearna** [comment]
Added the error message in a popup only for strains - i.e., the popup is not shown for genes and other datatypes

**Comment by valearna** [comment]
Modify the form to always get the entity added, including the WBStrainID

**Comment by valearna** [comment]
Can you test the 'add entity' component again @draciti @vanaukenk and let me know if everything looks good?

**Comment by vanaukenk** [comment]
@valearna 
It looks fine to me.  Thx.
@draciti - do you also want to double-check?

**Comment by draciti** [comment]
Will do!
________________________________

**Comment by vanaukenk** [comment]
One other thought.  If the Strain autocomplete is empty, but the user clicks on 'Add selected', they still get the message that strains in the final list have been replaced.
If the autocomplete field is empty, we should always present the pop-up message about  No entities selected.

**Comment by valearna** [comment]
Thanks @vanaukenk, I'll fix the pop-up messages

**Comment by valearna** [comment]
@vanaukenk I fixed the pop-up issue

**Comment by draciti** [comment]
All good, tested both adding new and existing strains, and pop-up functionality. Closing
