### ISSUE TITLE
No link to AFP form in dashboard for paper 00062137

### ISSUE THREAD

**Issue by valearna** [WormBase/author-first-pass#239]
The link does not appear in the paper status page

**Comment by valearna** [comment]
found a bug in the function that generates the link. The main two_email entry for the first author of this paper was deleted and only the entry in two_old_email remained. Two_old_email entries were matched case-sensitive and this was causing the bug. Changing to case-insensitive fixed the issue. The patch is now live on the production site

**Comment by valearna** [comment]
ready to test @draciti @vanaukenk

**Comment by draciti** [comment]
working  well. closing
