### ISSUE TITLE
Update text of email to remove 'corresponding'

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/author-first-pass#243]
In response to user feedback:

"I'm not corresponding"

We should update the text of our email message from:

We have identified you as the corresponding author for the recently published paper:

to:

We have identified you as an author for the recently published paper:

**Comment by vanaukenk** [comment]
Perhaps we should also update the first sentence on this page to remove 'corresponding':

https://mypapers.afp.textpressolab.com/

**Comment by valearna** [comment]
I created a separate ticket for the change to the author portal page: https://github.com/WormBase/author-first-pass/issues/245

The change to the author portal will be done as part of the new release (4.0) since there are a lot of other changes happening on that page.

**Comment by valearna** [comment]
Implemeted and deployed to production pipeline
