### ISSUE TITLE
Double check email address extraction

### ISSUE THREAD

**Issue by draciti** [WormBase/author-first-pass#244]
For this paper
http://tazendra.caltech.edu/~acedb/daniel/00062455_Huang22.pdf
only one author's email was extracted: [stephen.pak@wustl.edu](mailto:stephen.pak@wustl.edu)

**Comment by valearna** [comment]
I've debugged the code and Tim's email is extracted but discarded since it contains an extra "." at the end. I can improve the extraction by removing extra characters.

**Comment by valearna** [comment]
- Fixed code in wbtools to remove additional "." in email addresses
- Added code to extract email addresses on multiple lines broken at the @ sign, like in the following example:

you@
email.com

- Updated requirements file in AFP codebase to point to new wbtools version
