### ISSUE TITLE
Strains not extracted -Paper 00056039

### ISSUE THREAD

**Issue by draciti** [WormBase/author-first-pass#97]
NM2689, is a bona fide strain in WB

**Comment by valearna** [comment]
can we close this issue @draciti ?

**Comment by draciti** [comment]
I think so, especially because the strain bit will be streamlined by Paul D. @vanaukenk , what do you think?

**Comment by valearna** [comment]
Any updates on this issue @draciti @vanaukenk ? Can we close it?

**Comment by vanaukenk** [comment]
@valearna - I'll take a look again.

**Comment by vanaukenk** [comment]
I can autocomplete on NM2689 in the Phenotype OA.  
@valearna - does that mean the strain is now in obo_name_strain?

**Comment by valearna** [comment]
Yes @vanaukenk. Now I see it in obo_name_strain (WBStrain00044181).
