### ISSUE TITLE
send monthly notifications for new data submitted by authors to curators

### ISSUE THREAD

**Issue by valearna** [WormBase/author-first-pass#98]
Set up cron jobs that query the DB and search for new data submitted by authors.
Send list of paper ids and links to the form for papers positive to specific datatypes.

List of email addresses to be notified per data type in column 'curator email' of this document:

https://docs.google.com/spreadsheets/u/2/d/1sS_uAjBJ2r5H90Lam62Ai0HunjwvfjnklkFNrDoNXeU/edit#gid=1601232973

**Comment by valearna** [comment]
Can you confirm that the pipeline is working correctly @draciti @vanaukenk? From the logs I see that the digests have been emailed out on August 4th.

**Comment by draciti** [comment]
e-mail from August 4th received. This is good to close
